---
- name: Hello Events
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Start httpd server
      condition: event.payload.message == "httpd start"
      action:
        run_job_template:
          name: httpdサーバ起動
          organization: Ansible-Demo

    - name: Stop httpd server
      condition: event.payload.message == "httpd stop"
      action:
        run_job_template:
          name: httpdサーバ停止
          organization: Ansible-Demo
